export const ROLE_CATEGORIES = [
  {
    label: 'Coaching & Instruction',
    value: 'coaching-instruction',
    categoryValue: 'coaching',
    roles: [
      'Head Coach',
      'Assistant Coach',
      'Pitching Coach',
      'Hitting Coach',
      'Catching Coach',
      'Defensive Coach',
      'Base Coach',
      'Youth Coach',
      'Camp Instructor',
      'Private Instructor',
    ],
  },
  {
    label: 'Officiating',
    value: 'officiating',
    categoryValue: 'officiating',
    roles: [
      'Umpire',
      'Referee',
      'Line Judge',
      'Official Scorer',
      'Shot Clock Operator',
      'Head Official',
    ],
  },
  {
    label: 'Tournament & Event Operations',
    value: 'event-operations',
    categoryValue: 'operations',
    roles: [
      'Tournament Director',
      'Event Coordinator',
      'Field / Court Setup Crew',
      'Scoreboard Operator',
      'PA Announcer',
      'Gate / Ticket Staff',
      'Concessions Staff',
      'Parking Attendant',
      'Volunteer Coordinator',
    ],
  },
  {
    label: 'Medical & Safety',
    value: 'medical-safety',
    categoryValue: 'athletic-training',
    roles: [
      'Athletic Trainer',
      'Team Physician',
      'EMT / First Responder',
      'Physical Therapist',
      'Sports Nutritionist',
    ],
  },
  {
    label: 'Media & Support',
    value: 'media-support',
    categoryValue: 'media',
    roles: [
      'Photographer',
      'Videographer',
      'Social Media Manager',
      'Statistician',
      'Broadcaster / Play-by-Play',
      'Graphic Designer',
    ],
  },
  {
    label: 'Administrative',
    value: 'admin',
    categoryValue: 'admin',
    roles: [
      'League Administrator',
      'Registration Coordinator',
      'Office Manager',
      'Scheduler',
      'Compliance Officer',
      'Recruiting Coordinator',
    ],
  },
]
